---

- shell: >
    wget -qO- https://get.docker.io/gpg | sudo apt-key add - &&
    echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list &&
    apt-get update
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: install packages for docker
  apt: pkg={{item}} state=present
  with_items:
  - docker-engine
  - nfs-common

- file: path=/etc/docker state=directory mode=0755
- file: path=/etc/docker/tls state=directory mode=0755

- name: copy tls ca server files
  copy: src="{{ lookup('env', 'HOME')}}/.vm4docker/certs/{{item}}" dest="/etc/docker/tls/{{item}}" owner=root mode=0400
  with_items:
  - server-cert.pem
  - server-key.pem

- name: copy tls ca client files
  copy: src="{{ lookup('env', 'HOME')}}/.vm4docker/certs/{{item}}" dest="/etc/docker/tls/{{item}}" owner=root mode=0444
  with_items:
  - ca.pem
  - cert.pem
  - key.pem

- name: copy docker envs /etc/profile.d/
  copy: src="docker-client.sh" dest="/etc/profile.d/docker-client.sh" owner=root mode=0644

- name: add tls to docker daemon
  lineinfile: dest=/etc/default/docker line='DOCKER_OPTS="--tlsverify --tlscacert=/etc/docker/tls/ca.pem --tlscert=/etc/docker/tls/server-cert.pem --tlskey=/etc/docker/tls/server-key.pem -H=0.0.0.0:2376"'
  notify: restart docker

- stat: path=/Users
  register: users_path
- file: path=/Users state=directory
  when: not users_path.stat.exists

- name: fstab nfs
  lineinfile: dest=/etc/fstab line='{{ docker_gatewayip }}:/Users /Users nfs noatime,bg,rw,vers=3,tcp,actimeo=1800,rsize=262144,wsize=262144 0 0'
